var image_lookup = {
  "Able Bash": "https://s20.postimg.cc/kbgtdvth9/Able_Bash.png",
  "Able Bludgeon": "https://s20.postimg.cc/tj91ul899/Able_Bludgeon.png",
  "Able Stab": "https://s20.postimg.cc/r1xanbw2l/Able_Stab.png",
  "Absorbing Block": "https://s20.postimg.cc/89lfjr7e1/Absorbing_Block.png",
  "Accelerate Time": "https://s20.postimg.cc/l0zlqac15/Accelerate_Time.png",
  "Accelerated Thought": "https://s20.postimg.cc/6512ipnrt/Accelerated_Thought.png",
  "Acid Blast": "https://s20.postimg.cc/okljg3715/Acid_Blast.png",
  "Acid Jet": "https://s20.postimg.cc/nv2r3pr21/Acid_Jet.png",
  "Acid Pool": "https://s20.postimg.cc/reootjwcp/Acid_Pool.png",
  "Acid Spray": "https://s20.postimg.cc/8z47w4nd5/Acid_Spray.png",
  "Acorn Barrage": "https://s20.postimg.cc/d88xybdrt/Acorn_Barrage.png",
  "Acorn Bombardment": "https://s20.postimg.cc/a1eeepgh5/Acorn_Bombardment.png",
  "Acorn Sling": "https://s20.postimg.cc/rrg2zr1rt/Acorn_Sling.png",
  "Acrobatic Flip": "https://s20.postimg.cc/6ujuv3bgp/Acrobatic_Flip.png",
  "Adaptable": "https://s20.postimg.cc/3npbbgyqh/Adaptable.png",
  "Adapted to Acid": "https://s20.postimg.cc/ae5skwtm1/Adapted_to_Acid.png",
  "Adapted to Arcane": "https://s20.postimg.cc/89lfjtzp5/Adapted_to_Arcane.png",
  "Adapted to Cold": "https://s20.postimg.cc/l0zlqch6x/Adapted_to_Cold.png",
  "Adapted to Crushing": "https://s20.postimg.cc/x2uzkhy55/Adapted_to_Crushing.png",
  "Adapted to Electrical": "https://s20.postimg.cc/l0zlqcwmh/Adapted_to_Electrical.png",
  "Adapted to Fire": "https://s20.postimg.cc/c5yrfufjt/Adapted_to_Fire.png",
  "Adapted to Holy": "https://s20.postimg.cc/ijnuj3s5l/Adapted_to_Holy.png",
  "Adapted to Laser": "https://s20.postimg.cc/tw0g0w8k9/Adapted_to_Laser.png",
  "Adapted to Piercing": "https://s20.postimg.cc/mg16f3skp/Adapted_to_Piercing.png",
  "Adapted to Poison": "https://s20.postimg.cc/a1eees8s9/Adapted_to_Poison.png",
  "Adapted to Psychic": "https://s20.postimg.cc/okljg79mx/Adapted_to_Psychic.png",
  "Adapted to Radiation": "https://s20.postimg.cc/cvhjs8qe1/Adapted_to_Radiation.png",
  "Adapted to Slashing": "https://s20.postimg.cc/9on08mdnt/Adapted_to_Slashing.png",
  "Adapted to Sonic": "https://s20.postimg.cc/w0kt20zx5/Adapted_to_Sonic.png",
  "Adapted to Unholy": "https://s20.postimg.cc/52qw09zuh/Adapted_to_Unholy.png",
  "Advanced Battlefield Training": "https://s20.postimg.cc/kbgte218p/Advanced_Battlefield_Training.png",
  "Air Dance": "https://s20.postimg.cc/uyamjhotl/Air_Dance.png",
  "Alabaster Wyrmhide": "https://s20.postimg.cc/wq3leefw9/Alabaster_Wyrmhide.png",
  "All Out Attack": "https://s20.postimg.cc/4pzhu4k5l/All_Out_Attack.png",
  "Almighty Bludgeon": "https://s20.postimg.cc/8mctq4cux/Almighty_Bludgeon.png",
  "Almighty Hack": "https://s20.postimg.cc/qp5whcgfd/Almighty_Hack.png",
  "Altruism": "https://s20.postimg.cc/7wu1drzgp/Altruism.png",
  "Amorphous Body": "https://s20.postimg.cc/stq9ifprt/Amorphous_Body.png",
  "Ancient Statue": "https://s20.postimg.cc/r1xanjluh/Ancient_Statue.png",
  "Anvil Strike": "https://s20.postimg.cc/7wu1dsew9/Anvil_Strike.png",
  "Arcane Aura": "https://s20.postimg.cc/fctazlabd/Arcane_Aura.png",
  "Arcane Beam": "https://s20.postimg.cc/t6hnonamh/Arcane_Beam.png",
  "Arcane Burst": "https://s20.postimg.cc/dxrqavont/Arcane_Burst.png",
  "Arcane Curse": "https://s20.postimg.cc/cvhjscdk9/Arcane_Curse.png",
  "Arcane Feedback": "https://s20.postimg.cc/8mctq6i0p/Arcane_Feedback.png",
  "Arcane Shell": "https://s20.postimg.cc/ko87kbyyx/Arcane_Shell.png",
  "Arcane Spray": "https://s20.postimg.cc/cvhjsd0pl/Arcane_Spray.png",
  "Arcing Spark": "https://s20.postimg.cc/89lfk0mw9/Arcing_Spark.png",
  "Armor of Faith": "https://s20.postimg.cc/pmvpyvpx5/Armor_of_Faith.png",
  "Armor Practice": "https://s20.postimg.cc/wq3lei32h/Armor_Practice.png",
  "Arrogant Armor": "https://s20.postimg.cc/c5yrg0v15/Arrogant_Armor.png",
  "Attack Skill": "https://s20.postimg.cc/ko87kd99l/Attack_Skill.png",
  "Attack Soldier": "https://s20.postimg.cc/8z47weq0p/Attack_Soldier.png",
  "Attractive": "https://s20.postimg.cc/d88xyl0zt/Attractive.png",
  "Auto Block": "https://s20.postimg.cc/g2c3c1avt/Auto_Block.png",
  "Avenging Touch": "https://s20.postimg.cc/xsdrx2w6h/Avenging_Touch.png",
  "Backbiting Strike": "https://s20.postimg.cc/7k2n7pjsp/Backbiting_Strike.png",
  "Backfiring Breath": "https://s20.postimg.cc/sgyvcdpjd/Backfiring_Breath.png",
  "Bad For Them": "https://s20.postimg.cc/eaj4h5me1/Bad_For_Them.png",
  "Bad Luck": "https://s20.postimg.cc/bgfz3prxl/Bad_Luck.png",
  "Barbed Platemail": "https://s20.postimg.cc/4pzhuachl/Barbed_Platemail.png",
  "Barge": "https://s20.postimg.cc/tw0g14lhl/Barge.png",
  "Barrier of Hate": "https://s20.postimg.cc/8mctqacwp/Barrier_of_Hate.png",
  "Bash": "https://s20.postimg.cc/8z47wh2w9/Bash.png",
  "Battery Explosion": "https://s20.postimg.cc/hu5270749/Battery_Explosion.png",
  "Battleaxe Block": "https://s20.postimg.cc/77b91kr95/Battleaxe_Block.png",
  "Battleaxe Chop": "https://s20.postimg.cc/4d83o54ih/Battleaxe_Chop.png",
  "Battlefield Training": "https://s20.postimg.cc/c5yrg4i7d/Battlefield_Training.png",
  "Beam of Hate": "https://s20.postimg.cc/y5563c6rd/Beam_of_Hate.png",
  "Berserk Spin": "https://s20.postimg.cc/4r9fn6bl5/Berserk_Spin.png",
  "Big Zap": "https://s20.postimg.cc/yj6i2cqop/Big_Zap.png",
  "Bishop Acid": "https://s20.postimg.cc/41qnasvm1/Bishop_Acid.png",
  "Bishop Big Blast": "https://s20.postimg.cc/c78p901vd/Bishop_Big_Blast.png",
  "Bishop Blast": "https://s20.postimg.cc/dz1o3vy2x/Bishop_Blast.png",
  "Bishop Heal": "https://s20.postimg.cc/x44xdn515/Bishop_Heal.png",
  "Bishop Power": "https://s20.postimg.cc/lrsbvwecp/Bishop_Power.png",
  "Bishop Push": "https://s20.postimg.cc/rfymmrnu1/Bishop_Push.png",
  "Bishop Step": "https://s20.postimg.cc/nwcowz89l/Bishop_Step.png",
  "Bite": "https://s20.postimg.cc/rsq0syljd/Bite.png",
  "Blast": "https://s20.postimg.cc/d9ivrj595/Blast.png",
  "Blaze": "https://s20.postimg.cc/5gs7zl9kp/Blaze.png",
  "Bless": "https://s20.postimg.cc/po5nrwert/Bless.png",
  "Blessed Beacon": "https://s20.postimg.cc/3oz94p5nd/Blessed_Beacon.png",
  "Blind Rage": "https://s20.postimg.cc/njlaqtskp/Blind_Rage.png",
  "Blink": "https://s20.postimg.cc/mhb48jwzd/Blink.png",
  "Blizzard": "https://s20.postimg.cc/yj6i2fqpl/Blizzard.png",
  "Blizzard Breath": "https://s20.postimg.cc/nwcox2g09/Blizzard_Breath.png",
  "Blob of Slime": "https://s20.postimg.cc/kpi5de5u1/Blob_of_Slime.png",
  "Block": "https://s20.postimg.cc/m4jq24mcp/Block.png",
  "Block Link": "https://s20.postimg.cc/rfymmu0pl/Block_Link.png",
  "Block Soldier": "https://s20.postimg.cc/jagkoorw9/Block_Soldier.png",
  "Bloodied Block": "https://s20.postimg.cc/buhb2wbwp/Bloodied_Block.png",
  "Blooming Ground": "https://s20.postimg.cc/3oz94qvdl/Blooming_Ground.png",
  "Bludgeon": "https://s20.postimg.cc/5tjm5u4q1/Bludgeon.png",
  "Bludgeoning Branch": "https://s20.postimg.cc/t7rlhrud5/Bludgeoning_Branch.png",
  "Blunt Missile": "https://s20.postimg.cc/dma9xtxuh/Blunt_Missile.png",
  "Boiling Armor": "https://s20.postimg.cc/6vtsoeieh/Boiling_Armor.png",
  "Boosted Heal": "https://s20.postimg.cc/olvh9gj4p/Boosted_Heal.png",
  "Brachiation": "https://s20.postimg.cc/ikxscdosp/Brachiation.png",
  "Brain Burn": "https://s20.postimg.cc/jagkoqhmh/Brain_Burn.png",
  "Brainhook": "https://s20.postimg.cc/i86e67lyh/Brainhook.png",
  "Brains!": "https://s20.postimg.cc/540ttj1mh/Brains.png",
  "Brittle Flight Aura": "https://s20.postimg.cc/cwrhlifbd/Brittle_Flight_Aura.png",
  "Bronzantium Plates": "https://s20.postimg.cc/nwcox4dg9/Bronzantium_Plates.png",
  "Bronze Plates": "https://s20.postimg.cc/d9ivrpd0p/Bronze_Plates.png",
  "Bruiser": "https://s20.postimg.cc/6j2ei9xkp/Bruiser.png",
  "Brutal Charge": "https://s20.postimg.cc/7lcl0tvtl/Brutal_Charge.png",
  "Bull Rush": "https://s20.postimg.cc/vp3cp46kp/Bull_Rush.png",
  "Bungled Bolt": "https://s20.postimg.cc/fqumyzrs9/Bungled_Bolt.png",
  "Burning Blade": "https://s20.postimg.cc/vcbyiybg9/Burning_Blade.png",
  "Burning Fingers": "https://s20.postimg.cc/6j2eib05l/Burning_Fingers.png",
  "Buzzsaw": "https://s20.postimg.cc/qqfuam5cp/Buzzsaw.png",
  "Caltrops": "https://s20.postimg.cc/w1uqvbz55/Caltrops.png",
  "Catch Arrow": "https://s20.postimg.cc/4r9fnf3y1/Catch_Arrow.png",
  "Cause Fumble": "https://s20.postimg.cc/h5w7nr361/Cause_Fumble.png",
  "Cautious Sneak": "https://s20.postimg.cc/q0x1y9zo9/Cautious_Sneak.png",
  "Cave In": "https://s20.postimg.cc/wem51jjzt/Cave_In.png",
  "Chain Harness": "https://s20.postimg.cc/x44xdwctl/Chain_Harness.png",
  "Charge": "https://s20.postimg.cc/sv07bqwpl/Charge.png",
  "Charge Up": "https://s20.postimg.cc/41qnb35zd/Charge_Up.png",
  "Charged Laser Barrage": "https://s20.postimg.cc/oymvfrr5l/Charged_Laser_Barrage.png",
  "Charmed Block": "https://s20.postimg.cc/5gs7ztmi1/Charmed_Block.png",
  "Chilling Rime": "https://s20.postimg.cc/fe38sw9jd/Chilling_Rime.png",
  "Choking Bolt": "https://s20.postimg.cc/x44xdy2jt/Choking_Bolt.png",
  "Chop": "https://s20.postimg.cc/9pwy20cwp/Chop.png",
  "Cleansing Burst": "https://s20.postimg.cc/sv07bsu5l/Cleansing_Burst.png",
  "Cleansing Presence": "https://s20.postimg.cc/jagkowpe1/Cleansing_Presence.png",
  "Cleansing Ray": "https://s20.postimg.cc/yvxw8utmh/Cleansing_Ray.png",
  "Cloth Armor": "https://s20.postimg.cc/olvh9mj6h/Cloth_Armor.png",
  "Clubbing Branch": "https://s20.postimg.cc/8avddbtu1/Clubbing_Branch.png",
  "Clumsy": "https://s20.postimg.cc/ggdfbhxih/Clumsy.png",
  "Clumsy Chop": "https://s20.postimg.cc/eokggl6ft/Clumsy_Chop.png",
  "Cold Snap": "https://s20.postimg.cc/m4jq2ep09/Cold_Snap.png",
  "Combustible": "https://s20.postimg.cc/fe38symex/Combustible.png",
  "Cone of Cold": "https://s20.postimg.cc/wrdj7tpft/Cone_of_Cold.png",
  "Consecrate Ground": "https://s20.postimg.cc/nwcoxbnsp/Consecrate_Ground.png",
  "Consuming Spear": "https://s20.postimg.cc/pbe9m1h61/Consuming_Spear.png",
  "Contagion": "https://s20.postimg.cc/umt66rio9/Contagion.png",
  "Controlled Overswing": "https://s20.postimg.cc/wrdj7us0p/Controlled_Overswing.png",
  "Cooling Laser": "https://s20.postimg.cc/b4yiqu161/Cooling_Laser.png",
  "Corrosive Breath": "https://s20.postimg.cc/kcqr7jfy1/Corrosive_Breath.png",
  "Corrosive Touch": "https://s20.postimg.cc/y6f3wlvop/Corrosive_Touch.png",
  "Counterspell": "https://s20.postimg.cc/njlar72yx/Counterspell.png",
  "Cowardly": "https://s20.postimg.cc/wem51p4m1/Cowardly.png",
  "Cowardly Attack": "https://s20.postimg.cc/4ei1hetft/Cowardly_Attack.png",
  "Crafted Mail": "https://s20.postimg.cc/d9ivry5dl/Crafted_Mail.png",
  "Crippling Slash": "https://s20.postimg.cc/kcqr7kq8p/Crippling_Slash.png",
  "Crude Plates": "https://s20.postimg.cc/41qnb9lgp/Crude_Plates.png",
  "Crusher": "https://s20.postimg.cc/41qnb9t6h/Crusher.png",
  "Crushing Sweep": "https://s20.postimg.cc/bhpwx2wbd/Crushing_Sweep.png",
  "Curse of Fragility": "https://s20.postimg.cc/m4jq2hwqx/Curse_of_Fragility.png",
  "Cushioning Armor": "https://s20.postimg.cc/oymvfyecp/Cushioning_Armor.png",
  "Cut": "https://s20.postimg.cc/g3m15g4zt/Cut.png",
  "Dancing Cut": "https://s20.postimg.cc/x44xe4pqx/Dancing_Cut.png",
  "Dangerous Maneuver": "https://s20.postimg.cc/h5w7nzg3d/Dangerous_Maneuver.png",
  "Dash": "https://s20.postimg.cc/o9433mge1/Dash.png",
  "Dash Team": "https://s20.postimg.cc/3oz954sx5/Dash_Team.png",
  "Dastardly Curse": "https://s20.postimg.cc/r378h2qa1/Dastardly_Curse.png",
  "Dazing Bolt": "https://s20.postimg.cc/5tjm68hp5/Dazing_Bolt.png",
  "Deadly Spark": "https://s20.postimg.cc/8avddih15/Deadly_Spark.png",
  "Death Meld": "https://s20.postimg.cc/h5w7o0y3t/Death_Meld.png",
  "Defender s Block": "https://s20.postimg.cc/66b0cfuu1/Defender_s_Block.png",
  "Defense Skill": "https://s20.postimg.cc/5gs803209/Defense_Skill.png",
  "Defensiveness": "https://s20.postimg.cc/q0x1ykph5/Defensiveness.png",
  "Demon Hide": "https://s20.postimg.cc/ebt2albd5/Demon_Hide.png",
  "Demonic Feedback": "https://s20.postimg.cc/jagkp5a15/Demonic_Feedback.png",
  "Demonic Miasma": "https://s20.postimg.cc/o9433oljt/Demonic_Miasma.png",
  "Demonic Power": "https://s20.postimg.cc/b4yir017t/Demonic_Power.png",
  "Demonic Revenge": "https://s20.postimg.cc/as74ktqnt/Demonic_Revenge.png",
  "Desperate Block": "https://s20.postimg.cc/91o3ir18p/Desperate_Block.png",
  "Destructive Purge": "https://s20.postimg.cc/wsnh0vgvd/Destructive_Purge.png",
  "Devastating Blow": "https://s20.postimg.cc/rtzymc5cp/Devastating_Blow.png",
  "Devastating Spark": "https://s20.postimg.cc/5utjz5bnt/Devastating_Spark.png",
  "Devouring Touch": "https://s20.postimg.cc/tlsxh9455/Devouring_Touch.png",
  "Dimensional Traveller": "https://s20.postimg.cc/ath2don6h/Dimensional_Traveller.png",
  "Disenchant": "https://s20.postimg.cc/ubbptmru1/Disenchant.png",
  "Disorienting Block": "https://s20.postimg.cc/guerarp89/Disorienting_Block.png",
  "Dissolve Armor": "https://s20.postimg.cc/johwo7z49/Dissolve_Armor.png",
  "Dodge": "https://s20.postimg.cc/ubbpto24p/Dodge.png",
  "Dragon Claw": "https://s20.postimg.cc/3q96y3cm1/Dragon_Claw.png",
  "Drained Battery": "https://s20.postimg.cc/ykgfvtxo9/Drained_Battery.png",
  "Draining Filaments": "https://s20.postimg.cc/l3jhcyfmx/Draining_Filaments.png",
  "Draining Touch": "https://s20.postimg.cc/fs4ks9w55/Draining_Touch.png",
  "Dreadfully Ill": "https://s20.postimg.cc/g4vyyfyzd/Dreadfully_Ill.png",
  "Dropped Guard": "https://s20.postimg.cc/on5f2ssnd/Dropped_Guard.png",
  "Dual Laser Beacon": "https://s20.postimg.cc/s6rcslfxl/Dual_Laser_Beacon.png",
  "Duck": "https://s20.postimg.cc/vdlwc8nix/Duck.png",
  "Dwarven Battle Cry": "https://s20.postimg.cc/b68gjxxrd/Dwarven_Battle_Cry.png",
  "Dynamic Armor": "https://s20.postimg.cc/5utjz8r49/Dynamic_Armor.png",
  "Elemental Resistance": "https://s20.postimg.cc/6kccbljy1/Elemental_Resistance.png",
  "Elven Maneuvers": "https://s20.postimg.cc/wsnh0zjh5/Elven_Maneuvers.png",
  "Elven Trickery": "https://s20.postimg.cc/ath2dsacp/Elven_Trickery.png",
  "Elvish Insight": "https://s20.postimg.cc/9r6vv8z95/Elvish_Insight.png",
  "Elvish Mobility": "https://s20.postimg.cc/lgavj85nd/Elvish_Mobility.png",
  "Elvish Scamper": "https://s20.postimg.cc/x5ev76ow9/Elvish_Scamper.png",
  "Ember Burst": "https://s20.postimg.cc/pco7f7ycp/Ember_Burst.png",
  "Ember Spray": "https://s20.postimg.cc/7mmiu6shl/Ember_Spray.png",
  "Empower": "https://s20.postimg.cc/h765h2pjd/Empower.png",
  "Enabling Aura": "https://s20.postimg.cc/on5f2vso9/Enabling_Aura.png",
  "Enabling Ray": "https://s20.postimg.cc/4frzal2wp/Enabling_Ray.png",
  "Enchanted Harness": "https://s20.postimg.cc/i9gbzmg2h/Enchanted_Harness.png",
  "Enchanted Mail": "https://s20.postimg.cc/lgavjaat5/Enchanted_Mail.png",
  "Energize": "https://s20.postimg.cc/hjxjnaae1/Energize.png",
  "Energizing Move": "https://s20.postimg.cc/3q96y8a2x/Energizing_Move.png",
  "Enervating Touch": "https://s20.postimg.cc/r4h6a67ft/Enervating_Touch.png",
  "Enlarge": "https://s20.postimg.cc/3q96y94y1/Enlarge.png",
  "Entangle": "https://s20.postimg.cc/dastl51zt/Entangle.png",
  "Entangling Net": "https://s20.postimg.cc/vdlwcd5k9/Entangling_Net.png",
  "Entangling Roots": "https://s20.postimg.cc/agpo7pf95/Entangling_Roots.png",
  "Escaping Run": "https://s20.postimg.cc/4sjdgtimh/Escaping_Run.png",
  "Evasion": "https://s20.postimg.cc/xi69dguc9/Evasion.png",
  "Everlasting Ground": "https://s20.postimg.cc/55arn0gbt/Everlasting_Ground.png",
  "Extend": "https://s20.postimg.cc/67ky5l1q1/Extend.png",
  "Eyes Everywhere": "https://s20.postimg.cc/uo34017ll/Eyes_Everywhere.png",
  "Fate Reversal": "https://s20.postimg.cc/cy1ff01qh/Fate_Reversal.png",
  "Feedback Blast": "https://s20.postimg.cc/a3ya1kezt/Feedback_Blast.png",
  "Feinting Strike": "https://s20.postimg.cc/91o3j0ogp/Feinting_Strike.png",
  "Festering Guts": "https://s20.postimg.cc/4sjdgv8cp/Festering_Guts.png",
  "Fiery Breath": "https://s20.postimg.cc/ath2dy2op/Fiery_Breath.png",
  "Fiery Fist": "https://s20.postimg.cc/swa556695/Fiery_Fist.png",
  "Fiery Fists": "https://s20.postimg.cc/5i25t8w1l/Fiery_Fists.png",
  "Fiery Incantation": "https://s20.postimg.cc/79v4o6a9l/Fiery_Incantation.png",
  "Fiery Stab": "https://s20.postimg.cc/g4vyyobwp/Fiery_Stab.png",
  "Filch": "https://s20.postimg.cc/430l4jae1/Filch.png",
  "Fire Bolt": "https://s20.postimg.cc/lgavjedex/Fire_Bolt.png",
  "Fire Spray": "https://s20.postimg.cc/lgavjesuh/Fire_Spray.png",
  "Fireball": "https://s20.postimg.cc/yx7u2aavt/Fireball.png",
  "Fireproof Charm": "https://s20.postimg.cc/qrps4522h/Fireproof_Charm.png",
  "Firestarter": "https://s20.postimg.cc/ke0p0vpgp/Firestarter.png",
  "Firestorm": "https://s20.postimg.cc/ghnd4wrmh/Firestorm.png",
  "Flailing Bronze Fists": "https://s20.postimg.cc/hjxjng2q1/Flailing_Bronze_Fists.png",
  "Flame Jet": "https://s20.postimg.cc/t91jbfgu1/Flame_Jet.png",
  "Flame Spit": "https://s20.postimg.cc/vqdaiot0p/Flame_Spit.png",
  "Flanking Move": "https://s20.postimg.cc/c8in2rbih/Flanking_Move.png",
  "Flaring Laser": "https://s20.postimg.cc/cy1ff4jrt/Flaring_Laser.png",
  "Flash Flood": "https://s20.postimg.cc/wfw2v2ofd/Flash_Flood.png",
  "Flash of Agony": "https://s20.postimg.cc/y7p1pzfi1/Flash_of_Agony.png",
  "Flash of Arrows": "https://s20.postimg.cc/67ky5q6wp/Flash_of_Arrows.png",
  "Flash of Pain": "https://s20.postimg.cc/iyz4c7tjd/Flash_of_Pain.png",
  "Flimsy Block": "https://s20.postimg.cc/t91jbgr4p/Flimsy_Block.png",
  "Flowering Fungi": "https://s20.postimg.cc/iyz4c8oeh/Flowering_Fungi.png",
  "Flurry of Steel": "https://s20.postimg.cc/rtzymqxrd/Flurry_of_Steel.png",
  "Fly": "https://s20.postimg.cc/dastlcrrt/Fly.png",
  "Force Blast": "https://s20.postimg.cc/m5tnvvoa1/Force_Blast.png",
  "Force Bolt": "https://s20.postimg.cc/agpo7x515/Force_Bolt.png",
  "Force Cannon": "https://s20.postimg.cc/ozwt9cdll/Force_Cannon.png",
  "Force Cone": "https://s20.postimg.cc/bizuqgvk9/Force_Cone.png",
  "Force Field": "https://s20.postimg.cc/lgavjjqbd/Force_Field.png",
  "Forced Rotate": "https://s20.postimg.cc/ozwt9clbd/Forced_Rotate.png",
  "Forgetfulness": "https://s20.postimg.cc/k19auucdl/Forgetfulness.png",
  "Fork": "https://s20.postimg.cc/m5tnvx6ah/Fork.png",
  "Forward Thinking": "https://s20.postimg.cc/rtzymt2x5/Forward_Thinking.png",
  "Four- Headed Bite": "https://s20.postimg.cc/b68gkbvax/Four-_Headed_Bite.png",
  "Freeze": "https://s20.postimg.cc/c8in2vtjt/Freeze.png",
  "Freezing Fists": "https://s20.postimg.cc/ozwt9dvm1/Freezing_Fists.png",
  "Freezing Incantation": "https://s20.postimg.cc/6x3qi6f6x/Freezing_Incantation.png",
  "Frenzy Aura": "https://s20.postimg.cc/tlsxhr4ah/Frenzy_Aura.png",
  "Fright": "https://s20.postimg.cc/g4vyyw1op/Fright.png",
  "Frost Jolt": "https://s20.postimg.cc/dnk7rmpi1/Frost_Jolt.png",
  "Fumble": "https://s20.postimg.cc/cla193eeh/Fumble.png",
  "Gene Therapy": "https://s20.postimg.cc/5i25thgop/Gene_Therapy.png",
  "Genetic Boost": "https://s20.postimg.cc/z9z88ob7t/Genetic_Boost.png",
  "Genetic Engineering": "https://s20.postimg.cc/5utjzoee1/Genetic_Engineering.png",
  "Glob of Flame": "https://s20.postimg.cc/7mmiuld6h/Glob_of_Flame.png",
  "Good For Us": "https://s20.postimg.cc/3q96ylkh5/Good_For_Us.png",
  "Grasping Arms": "https://s20.postimg.cc/91o3jbtp5/Grasping_Arms.png",
  "Greased Armor": "https://s20.postimg.cc/r4h6ajhu1/Greased_Armor.png",
  "Greater Heal": "https://s20.postimg.cc/yx7u2j38p/Greater_Heal.png",
  "Greater Holy Insight": "https://s20.postimg.cc/fs4ksrwah/Greater_Holy_Insight.png",
  "Greater Spell Skill": "https://s20.postimg.cc/5jc3md0cp/Greater_Spell_Skill.png",
  "Grounding Plates": "https://s20.postimg.cc/h8g3abz15/Grounding_Plates.png",
  "Gusts of War": "https://s20.postimg.cc/b7ied9k4p/Gusts_of_War.png",
  "Hack": "https://s20.postimg.cc/6lma4x6bd/Hack.png",
  "Hard Tin Fist": "https://s20.postimg.cc/8q6n60fnt/Hard_Tin_Fist.png",
  "Hard to Pin Down": "https://s20.postimg.cc/8df8zu53t/Hard_to_Pin_Down.png",
  "Hardy Mail": "https://s20.postimg.cc/p16r2c7l5/Hardy_Mail.png",
  "Heal": "https://s20.postimg.cc/eecxwx75l/Heal.png",
  "Healing Beacon": "https://s20.postimg.cc/e1ljqqwll/Healing_Beacon.png",
  "Healing Benediction": "https://s20.postimg.cc/wtxeuc0pl/Healing_Benediction.png",
  "Healing Blessing": "https://s20.postimg.cc/y8yzj2h89/Healing_Blessing.png",
  "Healing Dash": "https://s20.postimg.cc/c9skvuso9/Healing_Dash.png",
  "Healing Presence": "https://s20.postimg.cc/vrn8bt51l/Healing_Presence.png",
  "Healing Pulse": "https://s20.postimg.cc/lhktckmvt/Healing_Pulse.png",
  "Healing Rays": "https://s20.postimg.cc/ylqdp9ud5/Healing_Rays.png",
  "Healing Spirit": "https://s20.postimg.cc/r5r43gyy1/Healing_Spirit.png",
  "Heat Treatment": "https://s20.postimg.cc/4h1x3x4pl/Heat_Treatment.png",
  "Heavy Armor": "https://s20.postimg.cc/3rj4rjwg9/Heavy_Armor.png",
  "Help the Weak": "https://s20.postimg.cc/e1ljqt9h5/Help_the_Weak.png",
  "Hemorrhage": "https://s20.postimg.cc/aur076hbd/Hemorrhage.png",
  "Hidebound": "https://s20.postimg.cc/fteilq0jt/Hidebound.png",
  "Hit the Deck": "https://s20.postimg.cc/nywkjvwih/Hit_the_Deck.png",
  "Holy Armor": "https://s20.postimg.cc/m73lozkvd/Holy_Armor.png",
  "Holy Insight": "https://s20.postimg.cc/tabh4ly0p/Holy_Insight.png",
  "Holy Presence": "https://s20.postimg.cc/gvop4ae89/Holy_Presence.png",
  "Horned Headbutt": "https://s20.postimg.cc/fteilr34p/Horned_Headbutt.png",
  "Horned Plates": "https://s20.postimg.cc/xjg76sofd/Horned_Plates.png",
  "Hot Flames": "https://s20.postimg.cc/dc2rehynt/Hot_Flames.png",
  "Hot Spot": "https://s20.postimg.cc/3rj4rmh1l/Hot_Spot.png",
  "Hover": "https://s20.postimg.cc/inhnz8fll/Hover.png",
  "Hurled Dagger": "https://s20.postimg.cc/b7iedfcgp/Hurled_Dagger.png",
  "Hurricane": "https://s20.postimg.cc/tn2vatyax/Hurricane.png",
  "Hypnotic Beacon": "https://s20.postimg.cc/gvop4c3yh/Hypnotic_Beacon.png",
  "Ice Bolts": "https://s20.postimg.cc/bk9sjmpll/Ice_Bolts.png",
  "Icy Block": "https://s20.postimg.cc/c9skvzxux/Icy_Block.png",
  "Ill-fitting Armor": "https://s20.postimg.cc/9fpfik3eh/Ill-fitting_Armor.png",
  "Illusory Barrier": "https://s20.postimg.cc/yyhrvkuo9/Illusory_Barrier.png",
  "Immovable": "https://s20.postimg.cc/sksosbxi1/Immovable.png",
  "Impaler": "https://s20.postimg.cc/68uvyy63t/Impaler.png",
  "Impaling Stab": "https://s20.postimg.cc/m73lp381l/Impaling_Stab.png",
  "Impenetrable Block": "https://s20.postimg.cc/j0925gvbd/Impenetrable_Block.png",
  "Impenetrable Nimbus": "https://s20.postimg.cc/j0925h315/Impenetrable_Nimbus.png",
  "Impetuous Blast": "https://s20.postimg.cc/8df9022ll/Impetuous_Blast.png",
  "Impetuous Heal": "https://s20.postimg.cc/bk9sjourd/Impetuous_Heal.png",
  "Impetuous Slash": "https://s20.postimg.cc/g65ws1o09/Impetuous_Slash.png",
  "Infected Bite": "https://s20.postimg.cc/80nutw7h5/Infected_Bite.png",
  "Inspiration": "https://s20.postimg.cc/a587uzgtl/Inspiration.png",
  "Inspirational Thinking": "https://s20.postimg.cc/sxk2ykkxl/Inspirational_Thinking.png",
  "Inspiring Armor": "https://s20.postimg.cc/9fpfimvpl/Inspiring_Armor.png",
  "Inspiring Presence": "https://s20.postimg.cc/kfamu8tuh/Inspiring_Presence.png",
  "Instant Burn": "https://s20.postimg.cc/luc7iz2nd/Instant_Burn.png",
  "Invisibility": "https://s20.postimg.cc/xw7ld4jll/Invisibility.png",
  "Jarring Block": "https://s20.postimg.cc/n9ds7pqvt/Jarring_Block.png",
  "Jump Back": "https://s20.postimg.cc/mjuzvcimh/Jump_Back.png",
  "Jump Soldier": "https://s20.postimg.cc/fgn4fqsmh/Jump_Soldier.png",
  "Jumpspark": "https://s20.postimg.cc/5w3hsvb09/Jumpspark.png",
  "Kindler": "https://s20.postimg.cc/gvop4h955/Kindler.png",
  "Large Weapon": "https://s20.postimg.cc/er4c3ef89/Large_Weapon.png",
  "Laser Barrage": "https://s20.postimg.cc/8q6n6c81l/Laser_Barrage.png",
  "Laser Beacon": "https://s20.postimg.cc/dc2reolux/Laser_Beacon.png",
  "Laser Block": "https://s20.postimg.cc/s81amacp5/Laser_Block.png",
  "Laser Bolt": "https://s20.postimg.cc/wh60ogno9/Laser_Bolt.png",
  "Laser Cutdown": "https://s20.postimg.cc/l4tf6ouex/Laser_Cutdown.png",
  "Laser Discharge": "https://s20.postimg.cc/czbd8iyg9/Laser_Discharge.png",
  "Laser Spray": "https://s20.postimg.cc/ks210ijux/Laser_Spray.png",
  "Laser Strike": "https://s20.postimg.cc/q3gxl8ld5/Laser_Strike.png",
  "Laser Thrust": "https://s20.postimg.cc/a587v3jfd/Laser_Thrust.png",
  "Laser Whip": "https://s20.postimg.cc/44aiy1jyh/Laser_Whip.png",
  "Lateral Thinking": "https://s20.postimg.cc/y8yzjehbt/Lateral_Thinking.png",
  "Launching Blow": "https://s20.postimg.cc/ks210jmft/Launching_Blow.png",
  "Lava Pool": "https://s20.postimg.cc/tzu9h98xl/Lava_Pool.png",
  "Leadership": "https://s20.postimg.cc/p16r2qcuh/Leadership.png",
  "Leap": "https://s20.postimg.cc/s81amchux/Leap.png",
  "Leather Harness": "https://s20.postimg.cc/68uvz5o61/Leather_Harness.png",
  "Leathery Hide": "https://s20.postimg.cc/fteim1l7t/Leathery_Hide.png",
  "Lesser Contagion": "https://s20.postimg.cc/44aiy31yx/Lesser_Contagion.png",
  "Lesser Spell Skill": "https://s20.postimg.cc/5w3hszt1l/Lesser_Spell_Skill.png",
  "Lifesaving Block": "https://s20.postimg.cc/inhnziajd/Lifesaving_Block.png",
  "Light Heal": "https://s20.postimg.cc/nywkk84bt/Light_Heal.png",
  "Lightning Bolt": "https://s20.postimg.cc/9fpfitiwp/Lightning_Bolt.png",
  "Lightning Breath": "https://s20.postimg.cc/8df90a7t5/Lightning_Breath.png",
  "Limited Heal": "https://s20.postimg.cc/tabh4ydjt/Limited_Heal.png",
  "Little Zap": "https://s20.postimg.cc/pqpjf5ijt/Little_Zap.png",
  "Loner": "https://s20.postimg.cc/zb9621fll/Loner.png",
  "Long Branch": "https://s20.postimg.cc/k2j8o9tmx/Long_Branch.png",
  "Long Spark": "https://s20.postimg.cc/pqpjf65p5/Long_Spark.png",
  "Lunging Bash": "https://s20.postimg.cc/dc2reulwp/Lunging_Bash.png",
  "Lunging Bite": "https://s20.postimg.cc/tn2vb6649/Lunging_Bite.png",
  "Lunging Hack": "https://s20.postimg.cc/56kpgpd3d/Lunging_Hack.png",
  "Lunging Strike": "https://s20.postimg.cc/7nwgnz4pl/Lunging_Strike.png",
  "Lunging Thrust": "https://s20.postimg.cc/4h1x4crzd/Lunging_Thrust.png",
  "Mad Dog": "https://s20.postimg.cc/a587v941l/Mad_Dog.png",
  "Magic in the Air": "https://s20.postimg.cc/9fpfiwyd5/Magic_in_the_Air.png",
  "Magma Spray": "https://s20.postimg.cc/5jc3mwq89/Magma_Spray.png",
  "Mail": "https://s20.postimg.cc/obnyqhuc9/Mail.png",
  "Martyr Blessing": "https://s20.postimg.cc/6lma5goh5/Martyr_Blessing.png",
  "Mass Frenzy": "https://s20.postimg.cc/er4c3mzvd/Mass_Frenzy.png",
  "Mass Invisibility": "https://s20.postimg.cc/6ydobnm6h/Mass_Invisibility.png",
  "Mass Reanimate": "https://s20.postimg.cc/nm56e643d/Mass_Reanimate.png",
  "Massive Chop": "https://s20.postimg.cc/czbd8qo89/Massive_Chop.png",
  "Massive Jaws": "https://s20.postimg.cc/cntwve7m1/Massive_Jaws.png",
  "Maze": "https://s20.postimg.cc/dq43dydkp/Maze.png",
  "Maze of the Mind": "https://s20.postimg.cc/aw0y0hvyx/Maze_of_the_Mind.png",
  "Meaty Goblin Fist": "https://s20.postimg.cc/h9q13r8kp/Meaty_Goblin_Fist.png",
  "Mega Laser": "https://s20.postimg.cc/gwymxl5qh/Mega_Laser.png",
  "Melt Armor": "https://s20.postimg.cc/aj9juc8k9/Melt_Armor.png",
  "Meltdown": "https://s20.postimg.cc/zcj3uzzah/Meltdown.png",
  "Memorisation": "https://s20.postimg.cc/947z5mmwp/Memorisation.png",
  "Memory Loss": "https://s20.postimg.cc/syu0rrhjt/Memory_Loss.png",
  "Mental Flensing": "https://s20.postimg.cc/p2govrouh/Mental_Flensing.png",
  "Mighty Bludgeon": "https://s20.postimg.cc/yzrpoubvt/Mighty_Bludgeon.png",
  "Mighty Charge": "https://s20.postimg.cc/sm2mllmfd/Mighty_Charge.png",
  "Mighty Hack": "https://s20.postimg.cc/syu0rrwzd/Mighty_Hack.png",
  "Mighty Limb Smash": "https://s20.postimg.cc/p2govsrfd/Mighty_Limb_Smash.png",
  "Mighty Spark": "https://s20.postimg.cc/947z5o4x5/Mighty_Spark.png",
  "Mimetic Armor": "https://s20.postimg.cc/u147acidl/Mimetic_Armor.png",
  "Mimetic Crown": "https://s20.postimg.cc/r711ww8hl/Mimetic_Crown.png",
  "Mind Drain": "https://s20.postimg.cc/qu9nqqdd5/Mind_Drain.png",
  "Mind Leak": "https://s20.postimg.cc/x7yqtzajd/Mind_Leak.png",
  "Mind Munch": "https://s20.postimg.cc/dq43e1t15/Mind_Munch.png",
  "Mind Worm": "https://s20.postimg.cc/9tqri2frd/Mind_Worm.png",
  "Mindless Battlerage": "https://s20.postimg.cc/m8djiemp5/Mindless_Battlerage.png",
  "Mini-torch": "https://s20.postimg.cc/57un9q1y1/Mini-torch.png",
  "Minor Heal": "https://s20.postimg.cc/rjsg34ghl/Minor_Heal.png",
  "Misguided Heal": "https://s20.postimg.cc/s9b8fhoqx/Misguided_Heal.png",
  "Missile Block": "https://s20.postimg.cc/iorlsm74p/Missile_Block.png",
  "Mob Attack": "https://s20.postimg.cc/8rgkzk78p/Mob_Attack.png",
  "Monkey Dodge": "https://s20.postimg.cc/6a4tsav21/Monkey_Dodge.png",
  "Monkey Mail": "https://s20.postimg.cc/tbley22fd/Monkey_Mail.png",
  "Monkey Maneuver": "https://s20.postimg.cc/h9q13x0wp/Monkey_Maneuver.png",
  "Monkey Punch": "https://s20.postimg.cc/liur63bvt/Monkey_Punch.png",
  "Mud Pit": "https://s20.postimg.cc/xkq508su1/Mud_Pit.png",
  "Muscle Through": "https://s20.postimg.cc/q4qvegcuh/Muscle_Through.png",
  "Mutated Chitin": "https://s20.postimg.cc/947z5s7ix/Mutated_Chitin.png",
  "Mystical Drakehide": "https://s20.postimg.cc/8ep6tfep5/Mystical_Drakehide.png",
  "Mystical Wyrmhide": "https://s20.postimg.cc/7cf0aw3ll/Mystical_Wyrmhide.png",
  "Nimble Strike": "https://s20.postimg.cc/yn0bite89/Nimble_Strike.png",
  "No Vital Organs": "https://s20.postimg.cc/k3t6hest5/No_Vital_Organs.png",
  "Noxious Breath": "https://s20.postimg.cc/xxhj6gt49/Noxious_Breath.png",
  "Numbing Blowdart": "https://s20.postimg.cc/xxhj6h0u1/Numbing_Blowdart.png",
  "Obliterating Bludgeon": "https://s20.postimg.cc/fhx292ufd/Obliterating_Bludgeon.png",
  "Obliterating Chop": "https://s20.postimg.cc/5km1g0ujd/Obliterating_Chop.png",
  "Obliterating Hack": "https://s20.postimg.cc/ya8xco695/Obliterating_Hack.png",
  "Obliterating Spark": "https://s20.postimg.cc/przh8c7g9/Obliterating_Spark.png",
  "Obvious Maneuver": "https://s20.postimg.cc/5km1g1hop/Obvious_Maneuver.png",
  "Officer s Harness": "https://s20.postimg.cc/aj9jukt7d/Officer_s_Harness.png",
  "Only Bones": "https://s20.postimg.cc/kgkknn8ix/Only_Bones.png",
  "Ooze Shove": "https://s20.postimg.cc/g7fulhczd/Ooze_Shove.png",
  "Ouch": "https://s20.postimg.cc/zcj3v8zd5/Ouch.png",
  "Over the Top": "https://s20.postimg.cc/6mw7ym32x/Over_the_Top.png",
  "Pact of Healing": "https://s20.postimg.cc/jr1sbb2uh/Pact_of_Healing.png",
  "Painful Beacon": "https://s20.postimg.cc/xxhj6jlfd/Painful_Beacon.png",
  "Paralytic Poison": "https://s20.postimg.cc/cntwvpkk9/Paralytic_Poison.png",
  "Paralyzing Bolt": "https://s20.postimg.cc/uqmzmx8p5/Paralyzing_Bolt.png",
  "Parry": "https://s20.postimg.cc/nnf47bip5/Parry.png",
  "Parrying Cut": "https://s20.postimg.cc/947z5xcpl/Parrying_Cut.png",
  "Parrying Strike": "https://s20.postimg.cc/45kgre16x/Parrying_Strike.png",
  "Path of Knives": "https://s20.postimg.cc/9gzdc3fjt/Path_of_Knives.png",
  "Pathfinding": "https://s20.postimg.cc/45kgregmh/Pathfinding.png",
  "Penetrating Bolt": "https://s20.postimg.cc/xxhj6lb5l/Penetrating_Bolt.png",
  "Penetrating Cut": "https://s20.postimg.cc/rjsg3cdzd/Penetrating_Cut.png",
  "Penetrating Lunge": "https://s20.postimg.cc/hz8tggwd5/Penetrating_Lunge.png",
  "Penetrating Stab": "https://s20.postimg.cc/o06idjqp5/Penetrating_Stab.png",
  "Penetrating Zap": "https://s20.postimg.cc/r711x6iux/Penetrating_Zap.png",
  "Perfect Block": "https://s20.postimg.cc/lvm5chc7t/Perfect_Block.png",
  "Perforating Strike": "https://s20.postimg.cc/ocxwjqoeh/Perforating_Strike.png",
  "Perplexing Ray": "https://s20.postimg.cc/pf832amnd/Perplexing_Ray.png",
  "Phase Shift": "https://s20.postimg.cc/przh8hcmx/Phase_Shift.png",
  "Pickpocket": "https://s20.postimg.cc/b8sc72yxl/Pickpocket.png",
  "Piercing Missile": "https://s20.postimg.cc/cb2ipma15/Piercing_Missile.png",
  "Pillar of Stone": "https://s20.postimg.cc/zcj3vdp49/Pillar_of_Stone.png",
  "Pinning Spear Toss": "https://s20.postimg.cc/5xdfmdsah/Pinning_Spear_Toss.png",
  "Planar Travel": "https://s20.postimg.cc/syu0s5f3d/Planar_Travel.png",
  "Poison Blowdart": "https://s20.postimg.cc/vsx65l9jt/Poison_Blowdart.png",
  "Poisoned Cut": "https://s20.postimg.cc/f55o3372h/Poisoned_Cut.png",
  "Poisoned Pseudopod": "https://s20.postimg.cc/ic07mqent/Poisoned_Pseudopod.png",
  "Poisoned Spear Stab": "https://s20.postimg.cc/6mw7yrvex/Poisoned_Spear_Stab.png",
  "Polearm Slash": "https://s20.postimg.cc/xxhj6p61l/Polearm_Slash.png",
  "Positioning Move": "https://s20.postimg.cc/tbleycs89/Positioning_Move.png",
  "Potent Spark": "https://s20.postimg.cc/nnf47gvll/Potent_Spark.png",
  "Potent Stab": "https://s20.postimg.cc/aw0y0ytjd/Potent_Stab.png",
  "Powerful Bash": "https://s20.postimg.cc/udvlgwy6x/Powerful_Bash.png",
  "Powerful Bludgeon": "https://s20.postimg.cc/kgkknuyax/Powerful_Bludgeon.png",
  "Powerful Hack": "https://s20.postimg.cc/8rgkzwf21/Powerful_Hack.png",
  "Powerful Spark": "https://s20.postimg.cc/rwju9o95l/Powerful_Spark.png",
  "Predictable Stab": "https://s20.postimg.cc/k3t6hovgp/Predictable_Stab.png",
  "Pressing Bash": "https://s20.postimg.cc/nanq1c321/Pressing_Bash.png",
  "Pseudopod Strike": "https://s20.postimg.cc/zcj3vh4kp/Pseudopod_Strike.png",
  "Psychic Barrage": "https://s20.postimg.cc/byb4jk22x/Psychic_Barrage.png",
  "Psychic Beam": "https://s20.postimg.cc/m8djiszo9/Psychic_Beam.png",
  "Psychic Blast": "https://s20.postimg.cc/57una522h/Psychic_Blast.png",
  "Pull the Trigger": "https://s20.postimg.cc/ddcp8aill/Pull_the_Trigger.png",
  "Puncturing Shot": "https://s20.postimg.cc/r711xcqmh/Puncturing_Shot.png",
  "Puncturing Stab": "https://s20.postimg.cc/syu0s9hp5/Puncturing_Stab.png",
  "Punishing Beam": "https://s20.postimg.cc/4v393z6y1/Punishing_Beam.png",
  "Punishing Bludgeon": "https://s20.postimg.cc/ml4xp0s8p/Punishing_Bludgeon.png",
  "Punishing Bolt": "https://s20.postimg.cc/5xdfmj56x/Punishing_Bolt.png",
  "Punishing Strike": "https://s20.postimg.cc/h9q14blll/Punishing_Strike.png",
  "Purge": "https://s20.postimg.cc/4v39401t5/Purge.png",
  "Purging Burst": "https://s20.postimg.cc/rxts2lau1/Purging_Burst.png",
  "Purging Strike": "https://s20.postimg.cc/kulwmyxop/Purging_Strike.png",
  "Push the Button": "https://s20.postimg.cc/947z66cs9/Push_the_Button.png",
  "Pushback Parry": "https://s20.postimg.cc/70xjxxkix/Pushback_Parry.png",
  "Queen Blast": "https://s20.postimg.cc/hazyx6pu1/Queen_Blast.png",
  "Quick Monkey Strike": "https://s20.postimg.cc/hnrd3d0e1/Quick_Monkey_Strike.png",
  "Quick Reactions": "https://s20.postimg.cc/i0ir9jy3d/Quick_Reactions.png",
  "Quick Rotate": "https://s20.postimg.cc/i0ir9k5t5/Quick_Rotate.png",
  "Quick Run": "https://s20.postimg.cc/xm02tiph5/Quick_Run.png",
  "Quick Step": "https://s20.postimg.cc/6o65rsk9l/Quick_Step.png",
  "Quickness Aura": "https://s20.postimg.cc/3u30ecadl/Quickness_Aura.png",
  "Radiation Bolt": "https://s20.postimg.cc/pgi0vdodl/Radiation_Bolt.png",
  "Radiation Bomb": "https://s20.postimg.cc/cp3uovmbd/Radiation_Bomb.png",
  "Radioactive Bite": "https://s20.postimg.cc/9v0pbfrux/Radioactive_Bite.png",
  "Radioactive Goo": "https://s20.postimg.cc/8sqiswgrd/Radioactive_Goo.png",
  "Radioactive Pulse": "https://s20.postimg.cc/mmevhyh2h/Radioactive_Pulse.png",
  "Radioactive Spray": "https://s20.postimg.cc/ida5fslix/Radioactive_Spray.png",
  "Raging Strike": "https://s20.postimg.cc/qis7dyhhl/Raging_Strike.png",
  "Raise the Alarm": "https://s20.postimg.cc/k534apkbd/Raise_the_Alarm.png",
  "Reaching Swing": "https://s20.postimg.cc/9v0pbh25l/Reaching_Swing.png",
  "Reactive Smoke Bomb": "https://s20.postimg.cc/demn1acl5/Reactive_Smoke_Bomb.png",
  "Reactive Trip": "https://s20.postimg.cc/cp3uoxjrd/Reactive_Trip.png",
  "Readiness": "https://s20.postimg.cc/khuigwxg9/Readiness.png",
  "Reanimate": "https://s20.postimg.cc/urwxg5v1l/Reanimate.png",
  "Redistribute": "https://s20.postimg.cc/5lvz9c1h5/Redistribute.png",
  "Reflect Missile": "https://s20.postimg.cc/mmevi0m89/Reflect_Missile.png",
  "Reflecting Block": "https://s20.postimg.cc/8sqisz1cp/Reflecting_Block.png",
  "Reflexive Teleport": "https://s20.postimg.cc/q60t7u4dl/Reflexive_Teleport.png",
  "Rejuvenation": "https://s20.postimg.cc/l7datbg09/Rejuvenation.png",
  "Reliable Hide Armor": "https://s20.postimg.cc/fvye8lm7t/Reliable_Hide_Armor.png",
  "Reliable Mail": "https://s20.postimg.cc/5lvz9dbrt/Reliable_Mail.png",
  "Resistant Hide": "https://s20.postimg.cc/m9nhbve95/Resistant_Hide.png",
  "Retaliatory Mutation": "https://s20.postimg.cc/tcvcrhreh/Retaliatory_Mutation.png",
  "Retreat": "https://s20.postimg.cc/yoa9c7swp/Retreat.png",
  "Reverse Rotate": "https://s20.postimg.cc/8fz4mu13d/Reverse_Rotate.png",
  "Reverse Scan": "https://s20.postimg.cc/4jlsquvjd/Reverse_Scan.png",
  "Righteous Frenzy": "https://s20.postimg.cc/jsbq4mwxl/Righteous_Frenzy.png",
  "Rocket Charge": "https://s20.postimg.cc/hazyxdkqx/Rocket_Charge.png",
  "Rocket Dash": "https://s20.postimg.cc/eto7q48k9/Rocket_Dash.png",
  "Rockfall": "https://s20.postimg.cc/a7s3hruqx/Rockfall.png",
  "Rook Acid": "https://s20.postimg.cc/gy8kr7pmh/Rook_Acid.png",
  "Rook Big Blast": "https://s20.postimg.cc/p3qmpdtax/Rook_Big_Blast.png",
  "Rook Blast": "https://s20.postimg.cc/8fz4mvqtl/Rook_Blast.png",
  "Rook Heal": "https://s20.postimg.cc/jfkbyhwo9/Rook_Heal.png",
  "Rook Push": "https://s20.postimg.cc/e45fdsibd/Rook_Push.png",
  "Rook Step": "https://s20.postimg.cc/axavu6dax/Rook_Step.png",
  "Rotate": "https://s20.postimg.cc/6berltzhl/Rotate.png",
  "Rotate Automatically": "https://s20.postimg.cc/fvye8p9e1/Rotate_Automatically.png",
  "Rumbling Charge": "https://s20.postimg.cc/glh6l2x2x/Rumbling_Charge.png",
  "Run": "https://s20.postimg.cc/w6yi51w6h/Run.png",
  "Run Team": "https://s20.postimg.cc/3u30ekv0p/Run_Team.png",
  "Rushing Aura": "https://s20.postimg.cc/dre17nprt/Rushing_Aura.png",
  "Rusty Armor": "https://s20.postimg.cc/fj702jtp5/Rusty_Armor.png",
  "Sapping Spear": "https://s20.postimg.cc/r8azqjfix/Sapping_Spear.png",
  "Savage Curse": "https://s20.postimg.cc/lk4ozn3gp/Savage_Curse.png",
  "Scabrous Skin": "https://s20.postimg.cc/u2e53zpex/Scabrous_Skin.png",
  "Scaly Armor": "https://s20.postimg.cc/6berlw4nd/Scaly_Armor.png",
  "Scamper": "https://s20.postimg.cc/snckfaj6x/Scamper.png",
  "Scamper Team": "https://s20.postimg.cc/9v0pboznd/Scamper_Team.png",
  "Scan": "https://s20.postimg.cc/lww35uobd/Scan.png",
  "Scared Little Monkey": "https://s20.postimg.cc/e45fdvxrt/Scared_Little_Monkey.png",
  "Scatter Laser": "https://s20.postimg.cc/95hwzd1op/Scatter_Laser.png",
  "Scorching Claws": "https://s20.postimg.cc/glh6l5x3t/Scorching_Claws.png",
  "Scouting Run": "https://s20.postimg.cc/x98onnzl5/Scouting_Run.png",
  "Scuttle": "https://s20.postimg.cc/9i9b5ketl/Scuttle.png",
  "Scuttle Team": "https://s20.postimg.cc/vhfpsrny1/Scuttle_Team.png",
  "Shambling Bash": "https://s20.postimg.cc/hazyxjsih/Shambling_Bash.png",
  "Shattering Sweep": "https://s20.postimg.cc/pgi0vpw6x/Shattering_Sweep.png",
  "Shield Block": "https://s20.postimg.cc/u2e542a09/Shield_Block.png",
  "Shifty Stab": "https://s20.postimg.cc/qis7e9mq1/Shifty_Stab.png",
  "Shimmering Aura": "https://s20.postimg.cc/nop20ts9l/Shimmering_Aura.png",
  "Short Blast": "https://s20.postimg.cc/glh6l829l/Short_Blast.png",
  "Short Missile": "https://s20.postimg.cc/mmeviah61/Short_Missile.png",
  "Short Perplexing Ray": "https://s20.postimg.cc/r8azqni4p/Short_Perplexing_Ray.png",
  "Short Spark": "https://s20.postimg.cc/mmevib4bd/Short_Spark.png",
  "Shotgun Slug": "https://s20.postimg.cc/snckfdynd/Shotgun_Slug.png",
  "Shotgun Spray": "https://s20.postimg.cc/mz69oihg9/Shotgun_Spray.png",
  "Shredding Strike": "https://s20.postimg.cc/q60t84u6h/Shredding_Strike.png",
  "Shrug it Off": "https://s20.postimg.cc/p3qmpl3nd/Shrug_it_Off.png",
  "Shuffle": "https://s20.postimg.cc/zdt1ouw3t/Shuffle.png",
  "Shuffle Team": "https://s20.postimg.cc/khuih959l/Shuffle_Team.png",
  "Simian Reflexes": "https://s20.postimg.cc/m9nhc5wc9/Simian_Reflexes.png",
  "Simple Bash": "https://s20.postimg.cc/x98ons26x/Simple_Bash.png",
  "Simple Strike": "https://s20.postimg.cc/a7s3i1a95/Simple_Strike.png",
  "Sizzling Bolt": "https://s20.postimg.cc/ba2a0l0s9/Sizzling_Bolt.png",
  "Skeletal Swarm": "https://s20.postimg.cc/6berm24p5/Skeletal_Swarm.png",
  "Skillful Dodge": "https://s20.postimg.cc/4wd6xcbbt/Skillful_Dodge.png",
  "Skillful Strike": "https://s20.postimg.cc/d1v8vi7ah/Skillful_Strike.png",
  "Skip": "https://s20.postimg.cc/khuihbafd/Skip.png",
  "Slicer": "https://s20.postimg.cc/4jlsr6vmx/Slicer.png",
  "Slippery": "https://s20.postimg.cc/k534b4zvd/Slippery.png",
  "Slowed": "https://s20.postimg.cc/sal69a8op/Slowed.png",
  "Small Pseudopod Strike": "https://s20.postimg.cc/jsbq4yx15/Small_Pseudopod_Strike.png",
  "Smashing Spin": "https://s20.postimg.cc/urwxgkv61/Smashing_Spin.png",
  "Smoke Bomb": "https://s20.postimg.cc/70xjyh2op/Smoke_Bomb.png",
  "Sneaky Bloodsuck": "https://s20.postimg.cc/46uel1889/Sneaky_Bloodsuck.png",
  "Solid Mail": "https://s20.postimg.cc/v4obms8ax/Solid_Mail.png",
  "Solid Wood": "https://s20.postimg.cc/q60t88ws9/Solid_Wood.png",
  "Soothing Darkness": "https://s20.postimg.cc/f6flwnlsp/Soothing_Darkness.png",
  "Sorcerous Blast": "https://s20.postimg.cc/y01et2rk9/Sorcerous_Blast.png",
  "Sorcerous Bolt": "https://s20.postimg.cc/g8psf7cbt/Sorcerous_Bolt.png",
  "Spark": "https://s20.postimg.cc/pujcuxb15/Spark.png",
  "Spark Generator": "https://s20.postimg.cc/6berm5cft/Spark_Generator.png",
  "Spark Inductor": "https://s20.postimg.cc/i1sp2ycrt/Spark_Inductor.png",
  "Sparking Breath": "https://s20.postimg.cc/ypk75gf95/Sparking_Breath.png",
  "Sparking Fists": "https://s20.postimg.cc/727hrd1s9/Sparking_Fists.png",
  "Sparking Incantation": "https://s20.postimg.cc/a921azty1/Sparking_Incantation.png",
  "Sparkling Cloth Armor": "https://s20.postimg.cc/5zxb8tyeh/Sparkling_Cloth_Armor.png",
  "Spawn Grub": "https://s20.postimg.cc/y01et4p09/Spawn_Grub.png",
  "Spawn Swarm": "https://s20.postimg.cc/484cdy9wp/Spawn_Swarm.png",
  "Spear of Darkness": "https://s20.postimg.cc/n0g7hij5l/Spear_of_Darkness.png",
  "Spear Thrust": "https://s20.postimg.cc/5aeiwhdah/Spear_Thrust.png",
  "Spell Skill": "https://s20.postimg.cc/jgu9rqbax/Spell_Skill.png",
  "Spell Train": "https://s20.postimg.cc/ly60z0amx/Spell_Train.png",
  "Spiked Mail": "https://s20.postimg.cc/84ho9yabt/Spiked_Mail.png",
  "Spore Cloud": "https://s20.postimg.cc/jtlnxxgq1/Spore_Cloud.png",
  "Spreading Laser": "https://s20.postimg.cc/ypk75j7k9/Spreading_Laser.png",
  "Sprint": "https://s20.postimg.cc/vipnlx2jt/Sprint.png",
  "Sprint Team": "https://s20.postimg.cc/6copf2e49/Sprint_Team.png",
  "Squeamish": "https://s20.postimg.cc/wxr8amvx5/Squeamish.png",
  "Squishy": "https://s20.postimg.cc/i1sp31zy1/Squishy.png",
  "Stab": "https://s20.postimg.cc/f7pjpm5hl/Stab.png",
  "Staggering Blow": "https://s20.postimg.cc/ycsszdzl5/Staggering_Blow.png",
  "Staggering Chop": "https://s20.postimg.cc/w88fyaq8p/Staggering_Chop.png",
  "Startling Strike": "https://s20.postimg.cc/ut6v9l4l5/Startling_Strike.png",
  "Sticky Bomb": "https://s20.postimg.cc/727hrhjtl/Sticky_Bomb.png",
  "Sticky Spittle": "https://s20.postimg.cc/8h92g7d6x/Sticky_Spittle.png",
  "Stink Bomb": "https://s20.postimg.cc/p50kipv3t/Stink_Bomb.png",
  "Stone Feet": "https://s20.postimg.cc/5zxb8y8q1/Stone_Feet.png",
  "Stone Spikes": "https://s20.postimg.cc/rz3pw64zt/Stone_Spikes.png",
  "Strong Bash": "https://s20.postimg.cc/ypk75lzvd/Strong_Bash.png",
  "Strong Bludgeon": "https://s20.postimg.cc/wxr8apvy1/Strong_Bludgeon.png",
  "Strong Chop": "https://s20.postimg.cc/irbhfhdd5/Strong_Chop.png",
  "Strong Hack": "https://s20.postimg.cc/jgu9rutc9/Strong_Hack.png",
  "Strong Stab": "https://s20.postimg.cc/7eyvxprtl/Strong_Stab.png",
  "Stunning Blow": "https://s20.postimg.cc/kvvugl9ux/Stunning_Blow.png",
  "Subtle Parry": "https://s20.postimg.cc/rmcbq14qh/Subtle_Parry.png",
  "Sundering Strike": "https://s20.postimg.cc/sbv42eczt/Sundering_Strike.png",
  "Super Team Heal": "https://s20.postimg.cc/z2blbufl5/Super_Team_Heal.png",
  "Supercharged Breath": "https://s20.postimg.cc/iek39cd3t/Supercharged_Breath.png",
  "Superstitious": "https://s20.postimg.cc/8h92gakxl/Superstitious.png",
  "Surestrike Blessing": "https://s20.postimg.cc/8h92gasnd/Surestrike_Blessing.png",
  "Surging Blast": "https://s20.postimg.cc/5n5x2uy6x/Surging_Blast.png",
  "Surging Bolt": "https://s20.postimg.cc/g9zq8alrt/Surging_Bolt.png",
  "Surging Shield Block": "https://s20.postimg.cc/xaimgyr3d/Surging_Shield_Block.png",
  "Swap": "https://s20.postimg.cc/dfwkuuz15/Swap.png",
  "Swarming Attack": "https://s20.postimg.cc/5aeiwp32h/Swarming_Attack.png",
  "Sweeping Smash": "https://s20.postimg.cc/5aeiwpii1/Sweeping_Smash.png",
  "Talented Healer": "https://s20.postimg.cc/zf2zi2vax/Talented_Healer.png",
  "Taunt": "https://s20.postimg.cc/a921b91qh/Taunt.png",
  "Team Heal": "https://s20.postimg.cc/zf2zi3aqh/Team_Heal.png",
  "Team Shift": "https://s20.postimg.cc/o2qe0bhh5/Team_Shift.png",
  "Team Walk": "https://s20.postimg.cc/qk257ktnt/Team_Walk.png",
  "Telekinesis": "https://s20.postimg.cc/fkgxvzio9/Telekinesis.png",
  "Telepod Jaunt": "https://s20.postimg.cc/phryp25pl/Telepod_Jaunt.png",
  "Teleport Other": "https://s20.postimg.cc/xna0n7m8p/Teleport_Other.png",
  "Thick Hide Armor": "https://s20.postimg.cc/ofhs6ium1/Thick_Hide_Armor.png",
  "Thickened Mail": "https://s20.postimg.cc/somi8p5l5/Thickened_Mail.png",
  "Thin Bludgeoning Branch": "https://s20.postimg.cc/g9zq8dlsp/Thin_Bludgeoning_Branch.png",
  "Thin Clubbing Branch": "https://s20.postimg.cc/irbhfndex/Thin_Clubbing_Branch.png",
  "Thunderblast": "https://s20.postimg.cc/j42vluiu1/Thunderblast.png",
  "Time Snap": "https://s20.postimg.cc/p50kiwq0p/Time_Snap.png",
  "Tongue Grab": "https://s20.postimg.cc/ut6v9t22x/Tongue_Grab.png",
  "Tongue Lash": "https://s20.postimg.cc/q7ar1gvzd/Tongue_Lash.png",
  "Tongue Storm": "https://s20.postimg.cc/4xn4qmneh/Tongue_Storm.png",
  "Totem Blast": "https://s20.postimg.cc/altfhizgp/Totem_Blast.png",
  "Totem Charge": "https://s20.postimg.cc/gmr4em1ih/Totem_Charge.png",
  "Touch of Death": "https://s20.postimg.cc/cqdsim8t5/Touch_of_Death.png",
  "Tough Bark": "https://s20.postimg.cc/4kvqkh7pl/Tough_Bark.png",
  "Tough Hide": "https://s20.postimg.cc/zf2zi75mh/Tough_Hide.png",
  "Toughened Hide Strips": "https://s20.postimg.cc/ly60zcaqh/Toughened_Hide_Strips.png",
  "Toughness": "https://s20.postimg.cc/ly60zcig9/Toughness.png",
  "Toxic Pulse": "https://s20.postimg.cc/484cebcl5/Toxic_Pulse.png",
  "Trained Bludgeon": "https://s20.postimg.cc/6copfelxl/Trained_Bludgeon.png",
  "Traveling Curse": "https://s20.postimg.cc/t1dwezb15/Traveling_Curse.png",
  "Tree Limb Smash": "https://s20.postimg.cc/e5fd7e7c9/Tree_Limb_Smash.png",
  "Tricky Stab": "https://s20.postimg.cc/qwtjdwou1/Tricky_Stab.png",
  "Trip": "https://s20.postimg.cc/d356ov3yh/Trip.png",
  "Triple Heals": "https://s20.postimg.cc/6copffoih/Triple_Heals.png",
  "Tripping Sweep": "https://s20.postimg.cc/somi8tvc9/Tripping_Sweep.png",
  "Troll Regeneration": "https://s20.postimg.cc/cdmeciqk9/Troll_Regeneration.png",
  "Twin Heals": "https://s20.postimg.cc/wkzu4tvrd/Twin_Heals.png",
  "Unfortunate Surge": "https://s20.postimg.cc/vipnmaknt/Unfortunate_Surge.png",
  "Unholy Curse": "https://s20.postimg.cc/jgu9s5j55/Unholy_Curse.png",
  "Unholy Energy": "https://s20.postimg.cc/r9kxk4wu1/Unholy_Energy.png",
  "Unholy Frenzy": "https://s20.postimg.cc/8u0gmqqfd/Unholy_Frenzy.png",
  "Unholy Wellspring": "https://s20.postimg.cc/kvvugwf3d/Unholy_Wellspring.png",
  "Unnerving Strike": "https://s20.postimg.cc/u3o2xltvd/Unnerving_Strike.png",
  "Unreliable Block": "https://s20.postimg.cc/nd7lo5ra1/Unreliable_Block.png",
  "Unstable Bolt": "https://s20.postimg.cc/iek39namh/Unstable_Bolt.png",
  "Unstoppable Chop": "https://s20.postimg.cc/a921bhu3d/Unstoppable_Chop.png",
  "Vegetable Parts": "https://s20.postimg.cc/ei6rdocs9/Vegetable_Parts.png",
  "Venomous Barbed Tail": "https://s20.postimg.cc/4xn4qsfqh/Venomous_Barbed_Tail.png",
  "Vicious Bite": "https://s20.postimg.cc/8h92glxvt/Vicious_Bite.png",
  "Vicious Thrust": "https://s20.postimg.cc/gmr4ertuh/Vicious_Thrust.png",
  "Violent Laser Barrage": "https://s20.postimg.cc/e5fd7ix3d/Violent_Laser_Barrage.png",
  "Violent Overswing": "https://s20.postimg.cc/irbhfv36x/Violent_Overswing.png",
  "Violent Spin": "https://s20.postimg.cc/u3o2xnjll/Violent_Spin.png",
  "Volcano": "https://s20.postimg.cc/6copfk6jt/Volcano.png",
  "Vulnerable": "https://s20.postimg.cc/5n5x36yah/Vulnerable.png",
  "Walk": "https://s20.postimg.cc/986dzkzrd/Walk.png",
  "Walk Team": "https://s20.postimg.cc/6pg3lqwjd/Walk_Team.png",
  "Wall of Fire": "https://s20.postimg.cc/lmt5zwyzd/Wall_of_Fire.png",
  "Wall of Illusion": "https://s20.postimg.cc/j5hesnmsp/Wall_of_Illusion.png",
  "Wall of Stone": "https://s20.postimg.cc/z3q4isoqh/Wall_of_Stone.png",
  "War Cry": "https://s20.postimg.cc/gbe9f8021/War_Cry.png",
  "Warp Run": "https://s20.postimg.cc/yqyqcmtm1/Warp_Run.png",
  "Weak Barge": "https://s20.postimg.cc/h0x1rl8bd/Weak_Barge.png",
  "Weak Block": "https://s20.postimg.cc/7gdf4pyex/Weak_Block.png",
  "Weak Chop": "https://s20.postimg.cc/dhb41ssqx/Weak_Chop.png",
  "Weak Javelin Toss": "https://s20.postimg.cc/61bug0crd/Weak_Javelin_Toss.png",
  "Weak Strike": "https://s20.postimg.cc/hqfu3zbft/Weak_Strike.png",
  "Weakened Armor": "https://s20.postimg.cc/flvh2whix/Weakened_Armor.png",
  "Whirlwind Enemies": "https://s20.postimg.cc/c29jd3u8p/Whirlwind_Enemies.png",
  "Wild Run": "https://s20.postimg.cc/kxadnmbbd/Wild_Run.png",
  "Wild Spark": "https://s20.postimg.cc/vwvkz8ovt/Wild_Spark.png",
  "Wimpy": "https://s20.postimg.cc/razgqvvmx/Wimpy.png",
  "Winds of War": "https://s20.postimg.cc/d4jpvo07d/Winds_of_War.png",
  "Wings of Faith": "https://s20.postimg.cc/bpi56yejt/Wings_of_Faith.png",
  "Wizard s Hat": "https://s20.postimg.cc/49ivl5j4p/Wizard_s_Hat.png",
  "Word of God": "https://s20.postimg.cc/9xp6c22wp/Word_of_God.png",
  "Wounded Block": "https://s20.postimg.cc/nem4uxky1/Wounded_Block.png",
  "Zap": "https://s20.postimg.cc/hqfu41obd/Zap.png",
  "Zombie Mob": "https://s20.postimg.cc/mcbycehk9/Zombie_Mob.png"
};